# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: Kimetrica Wiki
title: Kimetrica Wiki

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Kimetrica

description: Stylish Jekyll Theme
author:
  name: Kimetrica
  email: melissa.earl@kimetrica.com
  github: dbtek
  bio: For all your code dumping needs!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: <img src="/static/images/logo.30efce685dc1.png" alt="">

BASE_PATH:

gems:
  - jekyll-paginate
